### ISSUE TITLE
Error in installing pod

### ISSUE THREAD

**Issue by MehulSojitra16** [CodeEagle/SSImageBrowser#17]
I am using Xcode Version 8.3.1 and while installing cocoapod: [pod 'SSImageBrowser']() i'm getting following error.

[!] Error installing SSImageBrowser
[!] /usr/bin/git clone https://github.com/CodeEagle/SSImageBrowser.git /var/folders/1s/__q4tksn7mb_6kfcrh8787nh0000gn/T/d20170615-10037-y50sl0 --template= --single-branch --depth 1 --branch 2.0.9

Cloning into '/var/folders/1s/__q4tksn7mb_6kfcrh8787nh0000gn/T/d20170615-10037-y50sl0'...
warning: Could not find remote branch 2.0.9 to clone.
fatal: Remote branch 2.0.9 not found in upstream origin

**Comment by CodeEagle** [comment]
Tag  2.0.9 is not available. use 2.1.0 or latest tag 
`pod 'SSImageBrowser', :git => 'git@github.com:CodeEagle/SSImageBrowser.git'`

**Comment by tonifirnandes** [comment]
Sir, i am really sorry, could you please help us to provide older code "2.0.9", because we are still maintaining old xcode project using swift 2 and this library older version. I have posted the request in here : https://github.com/CodeEagle/SSImageBrowser/issues/18, if you don't mind would you like to looking or suggest something due that problem. Thanks.
